#!/bin/sh

set -e

if [ "$(id -u)" != "0" ]; then
    echo "Script must be run as root"
    exit 0
fi

if [ $# -ne 2 ]; then
echo "Usage $0 <image file> <mount dir>"
exit 1
fi

IMG=$1
MNT=$2

losetup /dev/loop0 $IMG
kpartx -as /dev/loop0
mount -t auto /dev/mapper/loop0p1 $MNT
mount --bind /dev $MNT/dev
mount --bind /proc $MNT/proc
mount --bind /sys $MNT/sys
chroot $MNT
umount $MNT/dev
umount $MNT/proc
umount $MNT/sys
umount $MNT
kpartx -d /dev/loop0
losetup -d /dev/loop0
